module.exports = {
  jwt: require("jsonwebtoken"),
  secret: require("../config/jwt.config.js"),
  User: require("../models/user.model.js"),
  expiresIn: require("../config/jwt.config"),
  Op: require("sequelize"),
  config: require(__dirname + "/../config/config.json")[env],
  fs: require("fs"),
  path: require("path"),
  Sequelize: require("sequelize"),
  process: require("process"),
  DataTypes: require("sequelize"),
  bcrypt: require("bcryptjs"),
  sequelize: require("./index.js"),
  express: require("express"),
  //router: express.Router(),
  authController: require("../controllers/auth.controller"),
  authenticate: require("../middlewares/auth.middleware"),
  dotenv: require("dotenv").config(),
  winston: require("winston"),
  morgan: require("morgan"),
  logger: require("../config/logger"),
  Order: require("../models/order.model"),
  //bcrypt: require("bcrypt"),
};
